version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "10000:10000"
    environment:
      - discovery.type=single-node
      - http.port=10000
